project_name: falco-exporter
before:
  hooks:
    - go mod tidy
builds:
  - id: "falco-exporter"
    goos:
    - linux
    goarch:
    - amd64
    - 386
    main: ./cmd/falco-exporter
    env:
      - CGO_ENABLED=0
    binary: falco-exporter

dockers:
  -
    goos: linux
    goarch: amd64
    skip_push: false
    dockerfile: build/Dockerfile
    image_templates:
      - "falcosecurity/falco-exporter:latest"
      - "falcosecurity/falco-exporter:{{ .Version }}"
      - "falcosecurity/falco-exporter:{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - cmd
      - pkg
      - go.mod
      - go.sum
      - Makefile

snapshot:
  name_template: 'master'

release:
  github:
  prerelease: auto