project_name: falco-exporter
before:
  hooks:
    - go mod tidy
builds:
  - id: "falco-exporter"
    goos:
    - linux
    goarch:
    - amd64
    - 386
    main: ./cmd/falco-exporter
    env:
      - CGO_ENABLED=0
    binary: falco-exporter

snapshot:
  name_template: 'master'

release:
  github:
  prerelease: auto