apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "falco-exporter.fullname" . }}
  labels:
    {{- include "falco-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "falco-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "falco-exporter.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "falco-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /usr/bin/falco-exporter
            - --client-hostname={{ .Values.falco.grpcHostname }}
            - --client-port={{ .Values.falco.grpcPort }}
            - --timeout={{ .Values.falco.grpcTimeout }}
            - --listen-address=0.0.0.0:{{ .Values.service.port }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/falco/certs
              name: certs-volume
              readOnly: true
      volumes:
        - name: certs-volume
          secret:
            secretName: {{ include "falco-exporter.fullname" . }}-certs
            items:
              - key: client.key
                path: client.key
              - key: client.crt
                path: client.crt
              - key: ca.crt
                path: ca.crt
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
