apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falco-exporter.fullname" . }}-certs
  labels:
    app: {{ include "falco-exporter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  client.key: {{ .Values.certs.client.key | b64enc | quote }}
  client.crt: {{ .Values.certs.client.crt | b64enc | quote }}
  ca.crt: {{ .Values.certs.ca.crt | b64enc | quote }}