---
# Source: falco-exporter/templates/secret-certs.yaml
apiVersion: v1
kind: Secret
metadata:
  name: falco-exporter-certs
  labels:
    app: falco-exporter
    chart: "falco-exporter-0.1.0"
    release: "falco-exporter"
    heritage: "Helm"
type: Opaque
data:
