---
# Source: falco-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: falco-exporter
  annotations:
    prometheus.io/port: "9376"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: falco-exporter
    app.kubernetes.io/instance: falco-exporter
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 9376
      targetPort: 9376
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: falco-exporter
    app.kubernetes.io/instance: falco-exporter
